### ISSUE TITLE
wiki doesn't respond after i login on CAS

### ISSUE THREAD

**Issue by Emi94** [CWRUChielLab/CASAuth#5]
Hello,
I have a server with MediaWiki 1.28 and phpCAS 1.3.5. On the wiki i press login, it sends me to the CAS login page and after i press login the page keeps loading saying "waiting for my.server.com..." until it times out and says "CAS Authentication failed!"
Do you have any idea what could cause this?

**Comment by jpgill86** [comment]
Hello @Emi94,

In my limited experience with MW 1.27 and earlier, I don't believe I have seen a timeout failure before.  Unfortunately, I do not have much time to work on this project now.  I hope someone else is able to help you!

Jeff

**Comment by Emi94** [comment]
I already fixed it, i should have closed the issue but i forgot about it. The problem was because the CAS server and the wiki were behind the same proxy(same public IP) and there was a loop on the firewall routing, but some internal DNS records solved the problem.
